websites:
  - name: Winco Fireworks
    url: https://www.wincofireworks.com/fireworks/
    scraper: winco_scraper
    enabled: false
    limit: 5
    note: >
      Uses WordPress/WooCommerce structure with srcset attributes.
      Product Metadata:
        - Title: h2.woocommerce-loop-product__title
        - Price: span.price
        - SKU: span.sku
        - Categories: nav.woocommerce-breadcrumb
        - Description: div.woocommerce-product-details__short-description
        - Stock Status: p.stock
        - Product Details:
          - Duration: Found in description
          - Shot Count: Found in description or title
          - Effects: Found in description
          - Size: Found in description
        - Additional Fields:
          - Warehouse Location: data-location attribute
          - Brand: Found in product categories
          - Product Type: Found in product categories
      Images:
        - Main Product Image: img.wp-post-image
        - Gallery Images: div.woocommerce-product-gallery__image
        - High-res URLs in srcset attribute
      Pagination: Standard WooCommerce with ?page=X parameter

  - name: Red Rhino Fireworks
    urls:
      - https://www.redrhinofireworks.com/firework-brands/red-rhino/
      - https://www.redrhinofireworks.com/firework-brands/hog-wild/
      - https://www.redrhinofireworks.com/firework-brands/subtle-fireworks/
      - https://www.redrhinofireworks.com/firework-brands/texas-outlaw/
    scraper: redrhino_scraper
    enabled: false
    limit: 5
    note: >
      Uses WordPress/Elementor structure.
      Product Images: Found in multiple locations:
        - div.elementor-widget-image img tags
        - figure elements with img tags
        - data-src attributes
        - Images are in year-based folders: /wp-content/uploads/YYYY/MM/
      Product Metadata:
        - Title: h1.elementor-heading-title
        - SKU: Found in text content
        - Description: Found in text content
      Image Handling:
        - Skips logo images (RR_brass)
        - Skips header/footer/banner images
        - Supports .jpg, .png, and .webp formats
      Directory Structure:
        - Images stored without www. prefix in domain folder

  - name: World Class Fireworks
    url: https://www.worldclassfireworks.com/fireworks/
    scraper: worldclass_scraper.py
    enabled: false
    limit: 5
    note: >
      Uses custom Shopify structure.
      Pagination: Uses 'Load More' button with data-url attribute.
      Product Grid: Uses 'product-item' class.
      Images: Found in '.product-item__image-container' with data-bgset attribute.
      Detail Pages: Contains higher resolution images in '.product__media-item'.
      Categories: Uses faceted filtering with 'collection-filters__item'.
      AJAX: Site loads more products dynamically via JSON responses.

  - name: Pyro Buy Fireworks
    url: https://www.pyrobuy.com/products.asp?sid=1&bid=1
    scraper: pyrobuy_scraper
    enabled: true
    limit: 5
    note: >
      Uses classic ASP structure with query parameters.
      Product Links: Found in productdtls.asp URLs.
      Product Details:
        - Name: Found in meta tag with property="og:title"
        - Image: Found in meta tag with property="og:image"
        - Image URLs: Usually in /video/thumb/ directory
        - Image Types: Mix of .png and .jpg files
      Pagination: 
        - Uses numbered links at bottom (1,2,3...)
        - Links contain ¤tpage parameter
      Categories: 
        - Uses sid parameter for sections
        - Uses bid parameter for brands
      Structure: 
        - Table-based layout with product cells
        - Product details in meta tags
        - Images hosted on both pyrobuy.com and dominatorfireworks.com domains

  - name: Raccoon Fireworks
    urls:
      - https://www.raccoonfireworksusa.com/monkey-mania-1
      - https://www.raccoonfireworksusa.com/raccoon-1-4g-1
    scraper: raccoon_scraper
    enabled: false
    limit: 5
    note: >
      Uses Wix platform with dynamic product pages.
      Product Links: Found in <a> tags with '/product-page/' in href.
      Images: Uses wixstatic.com CDN with configurable image parameters.
      Pagination: Successfully implemented using URL parameter '?page=X'.
      Product Images: Found in multiple locations:
        - wix-image with id="comp-image"
        - div with data-mesh-id containing "SITE_PAGES"
        - Any wixstatic.com media URLs not containing 'button', 'logo', 'icon'
      Image URL Modifications:
        - Replace '/v1/fill/[^/]+/' with '/v1/fill/w_1500,h_1500,al_c/'
        - Remove blur effects and other constraints
      Product Metadata:
        - Title: h1 tag with data-hook="product-title"
        - Price: span with data-hook="product-price"
        - SKU: span with data-hook="product-sku"
        - Description: div with data-hook="product-description"
        - Category: Found in breadcrumb with data-hook="breadcrumbs"
        - Stock Status: span with data-hook="product-inventory-status"
        - Weight/Size: Often in product description
        - Effects: Often in product description
      Database:
        - Products are stored with site_name and product_name as unique identifiers
        - Updates existing products if data changes
        - Stores both image_url and local_image_path
      Scraping Success:
        - Successfully downloads high-resolution product images
        - Handles pagination through multiple pages
        - Skips duplicate products
        - Maintains proper delays between requests
        - Logs detailed progress and results

  # Add more websites as needed:
  # - name: Store Name
  #   url: https://store-url.com
  #   enabled: true   # true means process this website
  #   limit: 5        # Examples:
                      # limit: -1  -> get all images from all pages
                      # limit: 1   -> get just one image
                      # limit: 50  -> get up to 50 images across all pages
                      # limit: 0   -> skip all images but still process the site